@baseUrl=http://localhost:6101
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY28wOTcwQG5hdmVyLmNvbSIsInN1YiI6IjUxZDkxN2ExLTUyZTctNDlkYi1hZGVhLTY2NmU0ZWNkMmZlMiIsImlhdCI6MTc1NjgwMTY5MiwiZXhwIjoxNzU2ODA1MjkyfQ.yUZcy_nQjVXC5g0zJJNKsJP0CmbIygXSuxJKdD2YYmY
@repoId=dc9b4deb-ab1f-40d5-b138-e3b9a5fd5276
@filePath=/Users/gimnayeon/Developments/capstone/git-project/biome.json

### (파일 업로드) 리포지토리에 파일 추가
POST {{baseUrl}}/repos/{{repoId}}/add
Authorization: Bearer {{token}}
# 1. Content-Type 헤더의 boundary 이름과
Content-Type: multipart/form-data; boundary=my-form-boundary

# 2. 본문의 boundary 이름이 일치해야 합니다.
--my-form-boundary
Content-Disposition: form-data; name="files"; filename="biome.json"

# 3. 👈 헤더와 파일 내용 사이에 반드시 '빈 줄'이 하나 있어야 합니다.
< {{filePath}}

# 4. 👈 요청의 끝을 알리는 마지막 경계선입니다. (양 끝에 --)
--my-form-boundary--